import { useState, useEffect } from 'react';
import { useStore } from '../store/useStore';
import { calculateBMI, getBMICategory, calculateTargetCalories } from '../utils/calculations';
import { Search, TrendingUp, TrendingDown, Minus, X, Award, Download } from 'lucide-react';
import { LineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer, AreaChart, Area } from 'recharts';

type Report = {
  userId: string;
  name: string;
  age: number;
  gender: string;
  bmi: number;
  bmiLabel: string;
  bmiColor: string;
  target: number;
  avgCals: number;
  currentWeight: number;
  diff: number;
  goal: string;
  conditions: string[];
  trend: 'improving' | 'stable' | 'declining';
  logs: any[];
};

// PDF Export function (generates a simple text-based report)
function exportToPDF(report: Report) {
  const content = `
NUTRITION PROGRESS REPORT
==========================
Generated: ${new Date().toLocaleDateString()}

PATIENT INFORMATION
-------------------
Name: ${report.name}
Age: ${report.age} years
Gender: ${report.gender}
Goal: ${report.goal === 'lose' ? 'Weight Loss' : report.goal === 'gain' ? 'Weight Gain' : 'Maintenance'}

HEALTH METRICS
--------------
BMI: ${report.bmi} (${report.bmiLabel})
Current Weight: ${report.currentWeight} kg
Weight Change: ${report.diff > 0 ? '+' : ''}${report.diff} kg
Daily Calorie Target: ${report.target} kcal
Average Intake: ${report.avgCals} kcal

HEALTH CONDITIONS
-----------------
${report.conditions.length > 0 ? report.conditions.join(', ') : 'None reported'}

PROGRESS STATUS
---------------
${report.trend === 'improving' ? '✓ On Track - Patient is meeting their nutrition goals' : 
  report.trend === 'declining' ? '⚠ Needs Attention - Recommend follow-up' : 
  '→ Stable - Progress is consistent'}

MEAL LOG SUMMARY
----------------
Total Days Logged: ${report.logs.length}
Average Daily Calories: ${report.avgCals} kcal

RECOMMENDATIONS
---------------
${report.trend === 'declining' ? '- Schedule a follow-up consultation\n- Review meal plan adherence\n- Consider adjusting calorie targets' : 
  report.trend === 'improving' ? '- Continue current meal plan\n- Maintain food logging consistency\n- Regular check-ins recommended' : 
  '- Monitor progress weekly\n- Ensure consistent meal logging'}

---
Generated by HealthyPlate
  `.trim();

  // Create and download text file (as simple PDF alternative)
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `progress-report-${report.name.replace(/\s+/g, '-')}-${new Date().toISOString().split('T')[0]}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export default function ProgressReport() {
  const { getAllPatients, getLogs } = useStore();
  const [patients, setPatients] = useState<{ user: User; profile: HealthProfile | null; lastLog: DailyLog | null }[]>([]);
  const [reports, setReports] = useState<Report[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [selected, setSelected] = useState<Report | null>(null);

  useEffect(() => {
    const loadReports = async () => {
      const allPatients = await getAllPatients();
      setPatients(allPatients);
      
      const reportsData = await Promise.all(
        allPatients
          .filter((p) => p.profile)
          .map(async ({ user, profile }) => {
            const logs = await getLogs(user.id);
            const bmi = calculateBMI(profile!.weight, profile!.height);
            const { label: bmiLabel, color: bmiColor } = getBMICategory(bmi);
            const target = calculateTargetCalories(profile!);
            const avgCals = logs.length
              ? Math.round(logs.reduce((s, l) => s + l.total_calories, 0) / logs.length)
              : 0;
            const weights = logs.filter((l) => l.weight).map((l) => l.weight!);
            const startWeight = weights[0] || profile!.weight;
            const currentWeight = weights[weights.length - 1] || profile!.weight;
            const diff = parseFloat((currentWeight - startWeight).toFixed(1));
            let trend: 'improving' | 'stable' | 'declining';
            if (profile!.goal === 'lose') trend = diff < -0.5 ? 'improving' : diff > 0.5 ? 'declining' : 'stable';
            else if (profile!.goal === 'gain') trend = diff > 0.5 ? 'improving' : diff < -0.5 ? 'declining' : 'stable';
            else trend = Math.abs(diff) < 1 ? 'improving' : 'stable';
            return { userId: user.id, name: user.name, age: profile!.age, gender: profile!.gender, bmi, bmiLabel, bmiColor, target, avgCals, currentWeight, diff, goal: profile!.goal, conditions: profile!.healthConditions, trend, logs };
          })
      );
      setReports(reportsData);
      setLoading(false);
    };
    loadReports();
  }, [getAllPatients, getLogs]);

  const filtered = reports.filter((r) => r.name.toLowerCase().includes(search.toLowerCase()));

  const trendChip = (trend: Report['trend']) => {
    if (trend === 'improving') return { label: 'On track', cls: 'bg-green-50 text-green-700', icon: <TrendingUp className="w-3 h-3" /> };
    if (trend === 'declining') return { label: 'Needs attention', cls: 'bg-red-50 text-red-600', icon: <TrendingDown className="w-3 h-3" /> };
    return { label: 'Stable', cls: 'bg-gray-100 text-gray-500', icon: <Minus className="w-3 h-3" /> };
  };

  const goalLabel = (g: string) => g === 'lose' ? 'Lose weight' : g === 'gain' ? 'Gain weight' : 'Maintain';

  return (
    <div className="p-6 max-w-5xl mx-auto">

      {/* Header + search */}
      <div className="flex items-end justify-between mb-6 gap-4 flex-wrap">
        <div>
          <h1 className="text-2xl font-bold text-gray-900" style={{ fontFamily: "'Playfair Display', serif" }}>
            Progress Reports
          </h1>
          <p className="text-gray-400 text-sm mt-1">{reports.length} patients · click a row to view full report</p>
        </div>
        <div className="relative">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
          <input
            type="text"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Search patient..."
            className="pl-9 pr-4 py-2.5 border border-gray-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-green-500 bg-white w-56"
          />
        </div>
      </div>

      {/* Table */}
      <div className="bg-white border border-gray-100 rounded-2xl shadow-sm overflow-hidden">
        <div className="grid grid-cols-[2fr_1fr_1fr_1fr_1fr_1fr] px-5 py-3 bg-gray-50 border-b border-gray-100 text-xs font-semibold text-gray-400 uppercase tracking-wide">
          <span>Patient</span>
          <span>BMI</span>
          <span>Target</span>
          <span>Avg Intake</span>
          <span>Weight &Delta;</span>
          <span>Status</span>
        </div>

        {filtered.length === 0 ? (
          <div className="py-16 text-center text-gray-400">
            <p className="text-3xl mb-2">🔍</p>
            <p className="text-sm">No patients found.</p>
          </div>
        ) : (
          filtered.map((r) => {
            const chip = trendChip(r.trend);
            return (
              <button
                key={r.userId}
                onClick={() => setSelected(r)}
                className="w-full grid grid-cols-[2fr_1fr_1fr_1fr_1fr_1fr] px-5 py-4 border-b border-gray-50 hover:bg-green-50 transition-colors text-left items-center last:border-b-0"
              >
                <div className="flex items-center gap-3">
                  <div className="w-9 h-9 rounded-full bg-green-100 flex items-center justify-center text-green-700 font-bold text-sm shrink-0">
                    {r.name.charAt(0)}
                  </div>
                  <div>
                    <p className="font-semibold text-gray-800 text-sm">{r.name}</p>
                    <p className="text-xs text-gray-400">{r.age} yrs · {goalLabel(r.goal)}</p>
                  </div>
                </div>
                <div>
                  <span className="font-semibold text-gray-800 text-sm">{r.bmi}</span>
                  <span className="block text-xs font-medium" style={{ color: r.bmiColor }}>{r.bmiLabel}</span>
                </div>
                <div>
                  <span className="text-sm text-gray-700">{r.target}</span>
                  <span className="block text-xs text-gray-400">kcal/day</span>
                </div>
                <div>
                  <span className={`text-sm font-semibold ${r.avgCals <= r.target ? 'text-green-600' : 'text-orange-500'}`}>{r.avgCals}</span>
                  <span className="block text-xs text-gray-400">kcal avg</span>
                </div>
                <div>
                  <span className={`text-sm font-semibold ${r.diff < 0 ? 'text-blue-500' : r.diff > 0 ? 'text-orange-400' : 'text-gray-400'}`}>
                    {r.diff > 0 ? '+' : ''}{r.diff} kg
                  </span>
                  <span className="block text-xs text-gray-400">{r.currentWeight} kg now</span>
                </div>
                <div>
                  <span className={`inline-flex items-center gap-1 text-xs font-semibold px-2.5 py-1 rounded-full ${chip.cls}`}>
                    {chip.icon}{chip.label}
                  </span>
                </div>
              </button>
            );
          })
        )}
      </div>

      {/* Detail Modal */}
      {selected && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center p-4"
          style={{ background: 'rgba(0,0,0,0.35)' }}
          onClick={() => setSelected(null)}
        >
          <div
            className="bg-white rounded-2xl shadow-2xl w-full max-w-2xl max-h-[90vh] overflow-y-auto"
            onClick={(e) => e.stopPropagation()}
          >
            {/* Modal header */}
            <div className="flex items-center justify-between px-6 py-5 border-b border-gray-100">
              <div className="flex items-center gap-3">
                <div className="w-11 h-11 rounded-full bg-green-100 flex items-center justify-center text-green-700 font-bold text-lg">
                  {selected.name.charAt(0)}
                </div>
                <div>
                  <h2 className="font-bold text-gray-900 text-lg">{selected.name}</h2>
                  <p className="text-sm text-gray-400">{selected.age} yrs · {selected.gender} · {goalLabel(selected.goal)}</p>
                </div>
              </div>
              <div className="flex items-center gap-2">
                <button
                  onClick={() => exportToPDF(selected)}
                  className="flex items-center gap-2 px-3 py-2 bg-green-600 text-white text-sm font-medium rounded-lg hover:bg-green-700 transition-colors"
                >
                  <Download className="w-4 h-4" />
                  Export Report
                </button>
                <button
                  onClick={() => setSelected(null)}
                  className="w-8 h-8 rounded-full bg-gray-100 hover:bg-gray-200 flex items-center justify-center transition-colors"
                >
                  <X className="w-4 h-4 text-gray-500" />
                </button>
              </div>
            </div>

            <div className="p-6 space-y-6">
              {/* Stats */}
              <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                {[
                  { label: 'BMI', val: String(selected.bmi), sub: selected.bmiLabel, subColor: selected.bmiColor },
                  { label: 'Calorie target', val: String(selected.target), sub: 'kcal / day', subColor: '#16a34a' },
                  { label: 'Avg consumed', val: String(selected.avgCals), sub: selected.avgCals <= selected.target ? 'Within target ✓' : 'Over target', subColor: selected.avgCals <= selected.target ? '#16a34a' : '#f97316' },
                  { label: 'Weight change', val: `${selected.diff > 0 ? '+' : ''}${selected.diff} kg`, sub: `Now ${selected.currentWeight} kg`, subColor: '#6b7280' },
                ].map(({ label, val, sub, subColor }) => (
                  <div key={label} className="bg-gray-50 rounded-xl px-4 py-3">
                    <p className="text-xs text-gray-400 mb-1">{label}</p>
                    <p className="text-xl font-bold text-gray-800">{val}</p>
                    <p className="text-xs font-medium mt-0.5" style={{ color: subColor }}>{sub}</p>
                  </div>
                ))}
              </div>

              {/* Conditions */}
              {selected.conditions.length > 0 && (
                <div>
                  <p className="text-sm font-semibold text-gray-600 mb-2">Health Conditions</p>
                  <div className="flex flex-wrap gap-2">
                    {selected.conditions.map((c) => (
                      <span key={c} className="bg-amber-50 border border-amber-200 text-amber-700 text-xs px-3 py-1 rounded-full">{c}</span>
                    ))}
                  </div>
                </div>
              )}

              {/* Calorie chart */}
              {selected.logs.length > 0 && (
                <div>
                  <p className="text-sm font-semibold text-gray-600 mb-3">Calorie Intake History</p>
                  <ResponsiveContainer width="100%" height={160}>
                    <AreaChart data={selected.logs.slice(-10).map((l: any) => ({
                      date: new Date(l.date).toLocaleDateString('en-PH', { month: 'short', day: 'numeric' }),
                      calories: l.total_calories,
                      target: selected.target,
                    }))}>
                      <defs>
                        <linearGradient id="cg2" x1="0" y1="0" x2="0" y2="1">
                          <stop offset="5%" stopColor="#22c55e" stopOpacity={0.25} />
                          <stop offset="95%" stopColor="#22c55e" stopOpacity={0} />
                        </linearGradient>
                      </defs>
                      <XAxis dataKey="date" tick={{ fontSize: 10 }} />
                      <YAxis tick={{ fontSize: 10 }} width={40} />
                      <Tooltip formatter={(v: any) => `${v} kcal`} />
                      <Area type="monotone" dataKey="calories" stroke="#22c55e" fill="url(#cg2)" strokeWidth={2} name="Consumed" />
                      <Line type="monotone" dataKey="target" stroke="#f97316" strokeDasharray="4 4" strokeWidth={1.5} dot={false} name="Target" />
                    </AreaChart>
                  </ResponsiveContainer>
                </div>
              )}

              {/* Weight chart */}
              {selected.logs.some((l: any) => l.weight) && (
                <div>
                  <p className="text-sm font-semibold text-gray-600 mb-3">Weight Trend</p>
                  <ResponsiveContainer width="100%" height={140}>
                    <LineChart data={selected.logs.filter((l: any) => l.weight).slice(-10).map((l: any) => ({
                      date: new Date(l.date).toLocaleDateString('en-PH', { month: 'short', day: 'numeric' }),
                      weight: l.weight,
                    }))}>
                      <XAxis dataKey="date" tick={{ fontSize: 10 }} />
                      <YAxis tick={{ fontSize: 10 }} width={40} domain={['auto', 'auto']} />
                      <Tooltip formatter={(v: any) => `${v} kg`} />
                      <Line type="monotone" dataKey="weight" stroke="#6366f1" strokeWidth={2} dot={{ r: 4 }} name="Weight (kg)" />
                    </LineChart>
                  </ResponsiveContainer>
                </div>
              )}

              {selected.trend === 'improving' && (
                <div className="flex items-center gap-2 bg-green-50 border border-green-200 rounded-xl px-4 py-3 text-sm text-green-700">
                  <Award className="w-4 h-4 shrink-0" />
                  Patient is on track with their nutrition goal!
                </div>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
